### PR TITLE
lxqt-session: Update man pages and make session the overview

### PR DESCRIPTION
**Pull request by jeremywh7**
Per the previous discussions in and related to https://github.com/lxde/lxqt-panel/pull/271, I've now made lxqt-session.1 include the LXQt module overview (which all the old man pages already state, actually), and simplified the remainder, trying to make them consistent.  I've also now similarly updated and rebased the lxqt-panel.1 in the above link.  I've tried my best to discern better descriptions of the modules, but you devs obviously know them better.  :)

### CODE REVIEW

**Comment by jeremywh7** [comment]
For a command-line preview, copy/paste these individually w/o quotes:
"curl -s https://raw.githubusercontent.com/jeremywh7/lxqt-session/master/lxqt-session/man/lxqt-session.1|man -l -"
"curl -s https://raw.githubusercontent.com/jeremywh7/lxqt-session/master/lxqt-config-session/man/lxqt-config-session.1|man -l -"
"curl -s https://raw.githubusercontent.com/jeremywh7/lxqt-session/master/lxqt-leave/resources/lxqt-leave.1|man -l -"

**Comment by jeremywh7** [comment]
@jleclanche @palinek @paulolieuthier @pmattern What do you guys think of the updated layout?  The lxqt-panel PR (link in OP) is all updated too, following the new layout structure.

**Comment by jeremywh7** [comment]
@jleclanche I don't follow; are you referring to one or all of these:
lxqt-config-session.1
lxqt-leave.1
lxqt-session.1
?

**Comment by palinek** [comment]
AFAICS the man page looks perfect.
Just `lxqt-sudo.1  LXQt sudo/su manager for application privilege elevation` -> it's not manager, just a GUI frontend.

**Comment by jleclanche** [comment]
@jeremywh7 I'm refering to the authorship section.

**Comment by jeremywh7** [comment]
@palinek @jleclanche Ok, I've got everything updated again.  Old author sections removed, lxqt-sudo references changed, and I also changed 'handler,' in general, to 'module.'  Also updated lxqt-panel PR...

**Comment by palinek** [comment]
GTM

**Comment by jeremywh7** [comment]
Updated session description of panel as per [PR 271](https://github.com/lxde/lxqt-panel/pull/271).

**Comment by jeremywh7** [comment]
@jleclanche What do you et al think of the new layout?  As in, the Session manual having the LXQt overview while other modules (Panel, etc) are intrinsically specific.  If this ok, I will go ahead with updating the other old module man pages accordingly.

**Comment by paulolieuthier** [comment]
Merged in 1dfc2e0b5baba6267c41c087170fa45d2694f3bc. Thanks.

**Pull request closed without merging**
