### PR TITLE
Adds a way to edit xdg user-dirs (Locations for Personal Files)

### PR DESCRIPTION
**Pull request by luis-pereira**
TODO:
- [x] Refactoring some vars names
- [x] Handle all translations the right way

Implementation of https://github.com/lxde/lxqt/issues/780

### CODE REVIEW

**Comment by paulolieuthier** [comment]
Just tested it and it's working well. GTM.

**Comment by jleclanche** [comment]
GTM from my side too.

**Comment by luis-pereira** [comment]
Rebased

**Comment by paulolieuthier** [comment]
Ship it.

**Comment by luis-pereira** [comment]
Take a look at the companion PR https://github.com/lxde/pcmanfm-qt/pull/234

**Pull request merged**
