### PR TITLE
lxqt-config-session: Addressing some of the issues at https://github.com/lxde/lxqt/issues/780

### PR DESCRIPTION
**Pull request by luis-pereira**
Discussion at https://github.com/lxde/lxqt/issues/780

### CODE REVIEW

**Comment by palinek** [comment]
GTM

**Comment by pmattern** [comment]
PR is fixing the naming in left pane and as such GTM.

Topic "clean form vs. set to `/home/<user>`" isn't affected by this PR but you're probably aware of this. Maybe we can go on discussing this in #780.

**Comment by luis-pereira** [comment]
@pmattern Yes. I'm aware that https://github.com/lxde/lxqt-session/commit/6542510e2536b88c9eb4ad4db26a27dba2dba9b8 doesn't address all the issues discussed in https://github.com/lxde/lxqt/issues/780.
I will address those issues and push to this PR.

**Comment by paulolieuthier** [comment]
GTM.

**Comment by luis-pereira** [comment]
Depends on https://github.com/lxde/libqtxdg/pull/78

**Comment by luis-pereira** [comment]
@pmattern Can you test ?

**Comment by luis-pereira** [comment]
Merged to get more testing.

**Pull request merged**
