### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by czchen**

### CODE REVIEW

**Comment by paulolieuthier** [comment]
Suggestion:  Through this applicaton you can manage settings related to applications startup and LXQt modules.

**Comment by czchen** [comment]
@paulolieuthier Thank for the suggestion.

**Comment by paulolieuthier** [comment]
@palinek is it ok for you now?

**Comment by palinek** [comment]
Now it seems correct to me.... but as I've said, I'm not naturaly english speaker. :)

**Comment by paulolieuthier** [comment]
Merged in cfba41659f01bd2531959efdc6f0f2255e2f8493. Thanks.

**Pull request closed without merging**
