### PR TITLE
Fix Japanese translations

### PR DESCRIPTION
**Pull request by u-ho-bros**
lxqt-config-session: Update Japanese translations.
lxqt-leave: Add Japanese translations.

### CODE REVIEW

**Comment by pmattern** [comment]
There are quite a lot of strings that got translated without removing attribute `type="unfinished"`, e. g. line 47 in `lxqt-config-session_ja.ts`. This should get fixed.
You may consider using Qt Linguist which automatically removes that attribute if translations are submitted by hitting `Enter`.

The use of *country*-specific translations should be consistent. If these are needed in Japanese, which I can't judge, *all* files should be available as respective translations, e. g. `foo_ja_JA.ts`.
If country-specific variants aren't needed in Japanese, language-specific translations like `foo_ja.ts` will do and any preexisting country-specific files can simply get dropped.

**Comment by u-ho-bros** [comment]
I was fixed has been pointed out places .
foo_ja_JA.ts was not needed.
Thank you.

**Comment by pmattern** [comment]
Actual translation seems good but two commits don't make sense and have to get squashed into one.

If you need help just let us know. We can also do it on behalf of you which does *not* change authorship.

**Comment by u-ho-bros** [comment]
I have summarized in one to commit the Japanese translation.
Are you sure you want to what to do?

**Comment by pmattern** [comment]
> Are you sure you want to what to do?

I'm sorry but I don't understand what you want to say here.

The PR itself looks perfectly good to me now. Without your last comment I'd certainly have merged (rebased) already.

**Comment by palinek** [comment]
>> Are you sure you want to what to do?

> I'm sorry but I don't understand what you want to say here.

It seems to me like some machine translation...

**Comment by u-ho-bros** [comment]
Sorry, I'm use the Google translation.
Please merge of the pull request.

**Comment by palinek** [comment]
> Sorry, I use the Google translation.

...now I'm going to be suspicious about the work done here. How can someone translate/localize english, if he/she doesn't understand english?

**Comment by luis-pereira** [comment]
I do agree with @palinek

**Comment by pmattern** [comment]
So do I by now.
@u-ho-bros Please don't be angry but before merging this should definitely get reviewed by at least one other native speaker.

**Comment by u-ho-bros** [comment]
Dear Sirs, One of my friends is native Speaker and I can ask his support on this. Will you kindly go forward for this?

**Comment by pmattern** [comment]
Not following. If you know someone that can review this translation it's fine but the next step would have go be that review and nothing at our side, no?

**Comment by rago1975** [comment]
Hi, I'm native Japanese, and I'm a member of LXDE translation project mailing list.  
I reviewed u-ho-bros's translation.  I think his translation is good, there is no need of any modification for his works.

**Comment by pmattern** [comment]
Alright then.

But I just saw in lxqt-config-session/translations/lxqt-config-session_ja.ts and lxqt-leave/translations/lxqt-leave_ja.ts attribute `language` is inconsistent with file name / intended translation and should just be `ja` instead of `ja_JA`.
This needs to be fixed (and the corresponding commit squashed into the current one again).

**Comment by rago1975** [comment]
I see. It should be fixed.
I will tell u-ho-bros what you pointed out, and I will help him to commit.

**Comment by u-ho-bros** [comment]
OK. I now done the check.

**Pull request merged**
